name: Release

jobs:
    Release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: fregante/release-with-changelog@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-template: '- {title} ← {hash}'
                  template: |
                      ### Changelog

                      {commits}

                      Compare : {range}

                      ❤
