name: Split

on:
    push:
        branches:
            - master

    release:
        types: [published]

jobs:
    split:
        name: Split
        runs-on: ubuntu-18.04

        steps:
            - name: "Checkout master"
              env:
                  GH_TOKEN: ${{ secrets.PRIVATE_WRITE_TOKEN }}
                  GH_REPO: "Elastic-Suite/magento2-elasticsuite-premium" # The repo to checkout.
                  REPO_LOCATION: "magento2-elasticsuite-premium/magento2-elasticsuite-premium" # This has to be the same as when using the checkout action.
              run: |
                git clone https://$GH_TOKEN@github.com/$GH_REPO master
                cd master && git checkout master

            - name: "Split repositories"
              env:
                  GH_TOKEN: ${{ secrets.PRIVATE_WRITE_TOKEN }}
              run: docker run --rm -e GH_TOKEN=$GH_TOKEN -v /cache:/cache/gitsplit -v $PWD/master:/srv jderusse/gitsplit
